### ISSUE TITLE
Unlocked filters not working anymore

### ISSUE THREAD

**Issue by matias200308** [ElJaviLuki/GrindrPlus#12]
You "unlocked" the functions, but they don't work, they are only activated for the application.
At least those that have to do with remote chats do work.

**Comment by RobbieTechie** [comment]
"It" did work and worked just fine.  Grindr recently did some changes server side to attempt to deal with this.  They are now up to version 8.14.1 of their app so I would guess soon 8.11.0 will force an upgrade soon.  I'm amazed they finally did this, as they seem clueless about the functioning of their own app quite frankly.  They appear to roll back their servers similiar to a windows restore point which unblocks users for many.  There have been reports of this on Reddit numerous times.

I would guess the recent changes are another attempt to push people to subscribe, yet they seem clueless overall about making this app worth-while to even use.  They've been generating fake profiles for a few years now (at least since the previous owners) at roughly 5-10 per second depending on server load.  Which would make it seem they are trying to artificially inflate the value of this sad state of an app.  They wish to push this public with stocks so they are attempting to make it's perceived value better while totally screwing their user base.  Their "expiring" photos never actually expire.  They don't remove old photos from their system, not even when a user deletes their account, and their cdn is not secure either.  Any photos you send don't leave their servers.  Also their data collection is completely out of control and has been for quite some time.  Certain countries have fined them for breaking those laws, yet they continue to break them and basically not care...

**Comment by ElJaviLuki** [comment]
Yeah, they don't work because they are now -and again- server-side features. So as long as they are server-side, I'm sorry to say there's nothing to do on that regard.
