### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by matias200308** [ElJaviLuki/GrindrPlus#13]
Will the app continue to be updated or has the project been abandoned?  I see that Grindr is already several versions ahead and the project has been two months without news

**Comment by ElJaviLuki** [comment]
I have life. This is a hobby for me -for now-: that is, I don't get paid for this -and I don't intend to, by the way-.

I will contribute to this project any time these conditions are met: will and time.

I understand that it's a hassle (as it is for me too) that because these projects aren't maintained as often as they require, Grindr still sucks.

With that being said, you all are free to help in the project by making a pull request.
